protocol.h: avoid redundant declaration of mavlink_helpers
otherwise, mavlink_helpers routines are defined twice - in protocol.h *and* in mavlink_helpers.h and i see warnings like:

In file included from src/mavlink/c_library/common/common.h:30:0,
                 from src/mavlink/c_library/common/mavlink.h:25,
                 from src/hostprotocol.h:8,
                 from src/dsm.h:5,
                 from src/dsm.cpp:1:
src/mavlink/c_library/common/../protocol.h:46:73: error: redundant redeclaration of 'mavlink_status_t* mavlink_get_channel_status(uint8_t)' in same scope [-Werror=redundant-decls]